let a = 10
let b = 30

try {
    
    
    let c = a * b + c

    console.log(c)

} catch (error) {

    console.log(error)
    
}finally{

    console.log("Fim da execução")

}